services:
  backend:
    image: maven:3.8.4-openjdk-17
    mem_limit: 500m
    cpus: 0.5
    volumes:
      - ./:/javamongo
    env_file:
      - ./.env
    ports:
      - 3000:8082
    command: /bin/sh -c "cd javamongo && mvn clean package -DskipTests && mv
      ./target/*.jar ./target/javamongo.jar &&  java -jar
      ./target/javamongo.jar"
  mongo:
    image: mongo:latest
    mem_limit: 500m
    cpus: 0.5
    env_file:
      - ./.env
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
