services:
  backend:
    image: python:3.12.1-slim
    depends_on:
      - database
    volumes:
      - ../../applications/api:/app
    ports:
      - "8000"
    env_file:
      - ./.env
    command: '/bin/sh -c "cd app && pip install -r requirements.txt && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"'
  database:
    image: postgres:14
    cpus: ${DB_CPUS}
    mem_limit: ${DB_MEMORY}
    env_file:
      - ./.env