version: "3.1"
services:
  backend:
    image: maven:3.8.4-openjdk-17
    # cpus: ${BK_CPUS}
    # mem_limit: ${BK_MEMORY}
    restart: always
    volumes:
      - ".:/java-mysql"
    env_file:
      - "./.env"
    environment:
       SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://db:3306/${MYSQL_DATABASE}",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "${MYSQL_ROOT_PASSWORD}",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQLDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    ports:
      - "8080:8080" 
    command: /bin/sh -c "cd java-mysql && mvn spring-boot:run" #mvn clean package -DskipTests && mvn spring-boot:run"
    depends_on:
      - db
  db:
    image: mysql
    restart: always
    # cpus: ${DB_CPUS}
    # mem_limit: ${DB_MEMORY}
    env_file:
      - "./.env"
