version: "3.1"
services:
  backend:
    image: maven:3.8.4-openjdk-17
    cpus: ${BK_CPUS}
    mem_limit: ${BK_MEMORY}
    volumes:
      - "../../applications/java-mysql:/java-mysql"
    env_file:
      - "./.env"
    environment:
       SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://db:3306/database",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "1234",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQLDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    ports:
      - 8080 
    # command: /bin/sh -c "cd java-mysql &&  mvn clean package -DskipTests && mvn spring-boot:run"
    command: /bin/sh -c "java -jar ./java-mysql/target/demo-0.0.1-SNAPSHOT.jar"
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql
    cpus: ${DB_CPUS}
    mem_limit: ${DB_MEMORY}
    env_file:
      - "./.env"
    environment:
      MYSQL_DATABASE: "database"
      MYSQL_ROOT_PASSWORD: "1234"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 30s 
      retries: 10
