version: "3.1"
services:
  backend:
    image: maven:3.8.4-openjdk-17
    cpus: ${BK_CPUS}
    mem_limit: ${BK_MEMORY}
    volumes:
      - "../../applications/java-postgres:/java-postgres"
    env_file:
      - "./.env"
    environment:
       SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:postgresql://db:5432/database",
        "spring.datasource.username" : "postgres",
        "spring.datasource.password" : "1234",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.PostgreSQLDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    ports:
      - 8080 
    # command: /bin/sh -c "cd java-postgres &&  mvn clean package -DskipTests && mvn spring-boot:run"
    command: /bin/sh -c "java -jar ./java-postgres/target/demo-0.0.1-SNAPSHOT.jar"
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:14 
    cpus: ${DB_CPUS}
    mem_limit: ${DB_MEMORY}
    env_file:
      - "./.env"
    environment:
      POSTGRES_DB: "database"
      POSTGRES_PASSWORD: "1234"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d database -h 127.0.0.1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
